name: myapp
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.12.0
  google_fonts: ^8.0.0
  url_launcher: ^6.3.2
  dio: ^5.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  open_filex: ^4.7.0
  flutter_animate: ^4.5.2
  flutter_dotenv: ^5.2.1
  animated_text_kit: ^4.3.0
  flutter_svg: ^2.0.10+1
  go_router: ^17.0.1
  intl: ^0.20.2
  flutter_riverpod: ^1.0.4
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - .env

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon-app.jpg"

  adaptive_icon_background: "#1A1A1A"
  adaptive_icon_foreground: "assets/icon/icon-app.jpg"

  web:
    generate: true
    image_path: "assets/icon/icon-app.jpg"
    background_color: "#1A1A1A"
    theme_color: "#D32F2F"

  windows:
    generate: true
    image_path: "assets/icon/icon-app.jpg"
    icon_size: 48 # Favicon size for Windows

  macos:
    generate: true
    image_path: "assets/icon/icon-app.jpg"

  linux:
    generate: true
    image_path: "assets/icon/icon-app.jpg"
